from datetime import datetime

from pydantic import BaseModel, Field


class PromptRequest(BaseModel):
    user_id: str = Field(
        ...,
        description="Unique identifier for the user to track conversation history",
        example="user_123",
    )

    specialization: str = Field(
        ...,
        description="User's professional specialization",
        example="Software Engineer",
    )

    request_description: str = Field(
        ...,
        description="Description of what the user wants the LLM to do",
        example="Generate a prompt to improve technical writing clarity",
    )


class PromptResponse(BaseModel):
    generated_prompt: str = Field(
        ..., description="The final prompt generated by the system"
    )

    retrieved_context_used: list[str] | None = Field(
        default=None, description="Optional debug field showing retrieved RAG context"
    )


class HistoryEntry(BaseModel):
    id: str = Field(..., description="MongoDB document ID")
    user_id: str
    user_request: str
    generated_prompt: str
    retrieved_context: list[str]
    timestamp: datetime


class HistoryResponse(BaseModel):
    history: list[HistoryEntry]
    total_count: int
